# Stage 1: Build the Frontend (Angular app)
FROM node:20.13.1 AS builder

WORKDIR /app

# Install Nx globally
RUN npm install -g nx

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the files and build the Angular app
COPY . .

# Set build configuration if provided (default to production)
RUN npx nx build mobile --configuration=production

# Stage 2: Serve the app with Nginx
FROM nginx:alpine

WORKDIR /app

# Copy the build output from the builder stage
COPY --from=builder /app/dist/apps/mobile/browser /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
